# Generated by Django 3.1.7 on 2021-04-27 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Изображение')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('publish', models.BooleanField(default=True)),
                ('sum_comments', models.IntegerField(default=0, verbose_name='Комментарии')),
                ('rating', models.IntegerField(default=0, verbose_name='Pейтинг')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='News_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=16, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='News_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('like', models.IntegerField(default=0, verbose_name='like')),
                ('dislike', models.IntegerField(default=0, verbose_name='dislike')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.news', verbose_name='Новость')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.news_category', verbose_name='Категория'),
        ),
    ]
