# Generated by Django 3.1.7 on 2021-04-09 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_categorysecond'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorysecond',
            name='cat_second_cat_first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_second', to='catalog.categoryfirst'),
        ),
    ]
