# Generated by Django 3.1.7 on 2021-04-09 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_categorysecond_cat_second_cat_first'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название товарной категории')),
                ('slug', models.SlugField(unique=True)),
                ('cat_goods_cat_second', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_goods', to='catalog.categorysecond')),
            ],
        ),
    ]
