# Generated by Django 3.1.7 on 2021-04-09 18:35

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods_in_basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Общая цена')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.basket', verbose_name='Корзина')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.good', verbose_name='Товар')),
            ],
        ),
    ]
