# Generated by Django 3.1.7 on 2021-04-09 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_specification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specification',
        ),
    ]
