# Generated by Django 3.1.7 on 2021-04-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_mobtel_television'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='television',
            options={'verbose_name': 'Television', 'verbose_name_plural': 'Televisions'},
        ),
    ]
