# Generated by Django 3.1.7 on 2021-04-15 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20210415_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_in_basket',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_in_basket', to='catalog.basket', verbose_name='Корзина'),
        ),
    ]
