# Generated by Django 3.1.7 on 2021-04-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20210415_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='goods',
            field=models.ManyToManyField(blank=True, related_name='related_basket', to='catalog.Goods_in_basket'),
        ),
    ]
