# Generated by Django 3.1.7 on 2021-04-17 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_basket_goods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods_in_basket',
            name='basket',
        ),
    ]
