# Generated by Django 3.1.7 on 2021-04-18 17:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20210417_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='total_price_basket',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Общая цена корзины'),
        ),
    ]
