# Generated by Django 3.1.7 on 2021-04-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobtel',
            name='about',
            field=models.CharField(max_length=250, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='television',
            name='about',
            field=models.CharField(max_length=250, verbose_name='Описание товара'),
        ),
    ]
