# Generated by Django 3.1.7 on 2021-04-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.FloatField(default=0, verbose_name='Курс'),
        ),
    ]
