# Generated by Django 3.1.7 on 2021-04-25 05:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_remove_course_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobtel',
            name='price_in_d',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=8, verbose_name='Цена в долларах'),
        ),
        migrations.AddField(
            model_name='television',
            name='price_in_d',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=8, verbose_name='Цена в долларах'),
        ),
        migrations.AlterField(
            model_name='mobtel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='television',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Цена'),
        ),
    ]
